### PR TITLE
Adding ADAL and o365 packages installation

### PR DESCRIPTION
**Pull request by JuanKRuiz**
The lab is missing instructions to get some **o365 references** not included in API tools for VS 2013, as well is missing **ADAL** installation required for some reference assemblies.

### CODE REVIEW

**Comment by ScotHillier** [comment]
I just made some changes today to address this. My changes were not as detailed, but can you look at what I did and comment back?

**Comment by JuanKRuiz** [comment]
Hi Scott, I just have arrived to Colombia today, let me review this tomorrow or Tuesday. Anyway thanks a lot :)

**Comment by JuanKRuiz** [comment]
It Looks perfect! yerterday We delivered an Office DevCamps and It ran smoothly!

thank you Scott!

**Comment by ScotHillier** [comment]
Great news! I so happy you were successful

Scot

Sent from my Windows Phone
________________________________

**Pull request closed without merging**
